/*
 * GDEWDotDisp.c
 *
 *  Created on: Sep 28, 2020
 *      Author: ubuntucomp
 */

#include "GDEWDotDisp.h"

void GDEW_BUSY()
{
while(!isEPD_W21_BUSY);
}

void GDEW_INIT(GDEW GDE)
{
	EPD_W21_Init();

	GDEW_PWR_SETTINGS(GDE.POWER);
	GDEW_BOOST_START(GDE.BST);
	GDEW_POWER_ON;
	GDEW_BUSY();

	EPD_W21_WriteCMD(GDEW_PAN_STG_CMD);
	EPD_W21_WriteDATA(GDEW_GET_PSR(GDE.PSR));

	GDEW_PLL_CNTL(GDE.PLL);
	GDEW_RESOLUTION_SETUP(GDE.width,GDE.height);
	GDEW_VCM_DC_STN(-1);
	GDEW_VCOM_DATA_SETTINGS(GDE.VCOM);
};

uint8_t GDEW_GET_PSR(GDEW_PSR PSR)
{
	return (PSR.RES<<6||PSR.LUT_S<<5||PSR.BWR<<4||PSR.GSD<<3 \
			||PSR.SHL<<2||PSR.SHDN<<1||PSR.RST);
}
void GDEW_PWR_SETTINGS(GDEW_POWER POWER)
{
	EPD_W21_WriteCMD(GDEW_PWR_STG_CMD);
	EPD_W21_WriteDATA(POWER.VDS_VDG);
	EPD_W21_WriteDATA(POWER.VCOM_HV);
	EPD_W21_WriteDATA(POWER.VDH_l);
	EPD_W21_WriteDATA(POWER.VDL_l);
	EPD_W21_WriteDATA(POWER.VDHR_l);
}

void GDEW_POWER_OFF_SEQ(GDEW_PWR_SEQ_SET PWR_SEQ)
{
	EPD_W21_WriteCMD(GDEW_POWER_OFF_SEQ_CMD);
	EPD_W21_WriteDATA(PWR_SEQ<<5);
}

void GDEW_BOOST_START(GDEW_BST_STR BST)
{
	EPD_W21_WriteCMD(GDEW_BOOSTED_SOFT_CMD);
	EPD_W21_WriteDATA(BST.PHASE_A);
	EPD_W21_WriteDATA(BST.PHASE_B);
	EPD_W21_WriteDATA(BST.PHASE_C);
}

void GDEW_PLL_CNTL(GDEW_PLL PLL)
{
	EPD_W21_WriteCMD(GDEW_PLL_CNTL_CMD);
	EPD_W21_WriteDATA(PLL);
}

void GDEW_SELECT_T_SENS(uint8_t sens,int T_OFFSET)
{
	EPD_W21_WriteCMD(GDEW_TEMP_SELECT_CMD);
	EPD_W21_WriteDATA((sens&0x01<<7)||GDEW_TEMP_OFFSET(T_OFFSET));
}

void GDEW_T_SENSOR_WRITE(GDEW_TEMP_SENSOR_WRITES WR)
{
	EPD_W21_WriteCMD(GDEW_TEMP_WRITE_CMD);
	uint8_t TEMP=WR.WBN<<6||WR.GDEW_I2C_DFN_ADDR<<3||WR.GDEW_I2C_PNT_SETTINGS;
	EPD_W21_WriteDATA(TEMP);
	EPD_W21_WriteDATA(WR.GDEW_I2C_WMSB);
	EPD_W21_WriteDATA(WR.GDEW_I2C_WLSB);
}

void GDEW_VCOM_DATA_SETTINGS(GDEW_VCOM_DATA VCOM)
{
	EPD_W21_WriteCMD(GDEW_VCOM_DATAITR_CMD);
	uint8_t temp = VCOM.VBD<<6||VCOM.DDX<<4||GDEW_CDI(VCOM.CDI);
	EPD_W21_WriteDATA(temp);
}


void GDEW_TCON_SETTINGS(uint8_t Period)
{
	EPD_W21_WriteCMD(GDEW_TCON_STN_CMD);
	EPD_W21_WriteDATA(Period-4);

}

void GDEW_RESOLUTION_SETUP(uint16_t width, uint8_t height)
{
	EPD_W21_WriteCMD(GDEW_RSN_STN_CMD);
	EPD_W21_WriteDATA(height<<3);
	EPD_W21_WriteDATA(width&0xFF);
	EPD_W21_WriteDATA(width>>8&0xFF);
}

void GDEW_AUTO_MESUARE(GDEW_AUTO_MSR_VCOM AUTOMSR)
{
	EPD_W21_WriteCMD(GDEW_AUTO_MSR_VCOM_CMD);
	uint8_t temp=AUTOMSR.AMVT<<4||AUTOMSR.XON<<3||AUTOMSR.AMVS<<2||AUTOMSR.AMV<<1||AUTOMSR.AMVE;
	EPD_W21_WriteDATA(temp);
}


void GDEW_VCM_DC_STN(float V)
{
	EPD_W21_WriteCMD(GDEW_VCM_DC_STN_CMD);
	uint8_t TEMP=(abs(V)*100-10)/5;
	EPD_W21_WriteDATA(TEMP);
}

void GDEW_PARTIAL_WINDOW_SELECT(uint8_t XSTART, uint8_t XEND, \
		uint16_t YSTART, uint16_t YEND, uint8_t Partial)
{
	GDEW_PARTIAL_MOD_SET;

	EPD_W21_WriteCMD(GDEW_PRT_W_CMD);

	EPD_W21_WriteDATA((XSTART<<3)&0XFF);
	EPD_W21_WriteDATA(((XEND<<3)||0X07)&0XFF);

	EPD_W21_WriteDATA((YSTART>>8)&0XFF);
	EPD_W21_WriteDATA(YSTART&0XFF);


	EPD_W21_WriteDATA((YEND>>8)&0XFF);
	EPD_W21_WriteDATA(YEND&0XFF);

	EPD_W21_WriteDATA(Partial&0x01);
}
void GDEW_READ_OTP();
uint8_t GDEW_CDI(uint8_t number){return (17-number);}
uint8_t GDEW_TEMP_OFFSET(int A)
{
	if(A<0) return 0x08||(8-A);
	else return A;
};


